version: '3'
services:
  server:
    container_name: pm2.5_server
    restart: always
    build: .
    ports:
      - '82:8080'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      # mapped a named volume inside host filesystem to the /data/db, where the mongodb put data
      - "my-db:/data/db"
    ports: 
      - '27017:27017'
volumes:
  my-db:
    external:
      name: my-db
